name: Query Releases

on:
  push:
    tags:
      - '*-[v]?[0-9]+.[0-9]+.[0-9]+'
      - '*-[v]?[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+'
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
    branches:
      - main
      - "release/*"

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Query Releases
        uses: ./.github/actions/query-releases
        id: query
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.event.repository.owner.login }}

      - uses: actions/download-artifact@v3
        with:
          name: releases

      - name: print
        run: |
          cat "releases.json" | jq
