name: Release Charts

on:
  push:
    tags:
      - '*-[v]?[0-9]+.[0-9]+.[0-9]+'
      - '*-[v]?[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+'
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
    branches:
      - main
      - "release/*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating releases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install main dependencies
        run: |
          apt-get update
          apt-get install yq jq

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
